# Generated by Django 4.1.7 on 2023-03-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_postform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postForm',
        ),
    ]
